# Generated by Django 4.1.7 on 2023-03-14 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
