# Generated by Django 4.1.7 on 2023-03-14 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('landing', '0003_rename_subscriber_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
