# Generated by Django 4.1.7 on 2023-03-20 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_productinorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='status',
        ),
    ]
