# Generated by Django 4.1.7 on 2023-03-20 03:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_orders_customer_address_orders_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
