# Generated by Django 4.1.7 on 2023-03-22 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0005_rename_total_amount_orders_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in order', 'verbose_name_plural': 'Products in order'},
        ),
    ]
