# Generated by Django 4.1.7 on 2023-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0007_productinbasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
