# Generated by Django 4.1.7 on 2023-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_products_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
