# Generated by Django 4.1.7 on 2023-03-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_productscategory_products_discount_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=49, null=True),
        ),
    ]
